### ISSUE TITLE
Cannot see inactive displays

### ISSUE THREAD

**Issue by waldner** [MartinGC94/DisplayConfig#12] opened 2024-11-11 22:37 UTC
See this for example:

![displays](https://github.com/user-attachments/assets/6045ba34-8e09-4969-a261-c49bb1f5c964)

With Windows, I can select display 2 and enable it, extend desktop to it, etc.

But DisplayConfig shows this:

```
PS C:\Users\admin> Get-DisplayInfo

 DisplayId DisplayName      Active  Primary Position    Mode                  ConnectionType
 --------- -----------      ------  ------- --------    ----                  --------------
         1 QEMU Monitor       True    False -1024 0     1024x768@1 Hz                  Other
         2 D1150-PL2.0        True     True 0 0         1024x768@60.00384...            HDMI
         3 D1150-PL2.0        True    False 1024 0      1024x768@60.00384...            HDMI

```

So not only is the display Windows identifies as "2" missing from this output (it's a VGA-connected monitor), but those that are seen have a different numbering. Is this intended, and is there a workaround?

**Comment by MartinGC94** [comment] 2024-11-11 22:59
When I researched the API I saw something about forced output for analog connection types like VGA but I figured it wasn't necessary to think about in 2024 but I guess I was wrong about that.

I think I know what changes I need to make but I will need your help to test it because I don't have a VGA compatible system/display.

Can you send me a copy of your displayconfig before and after you enable the display in the settings app? You can export them with: `Get-DisplayConfig | Export-Clixml $HOME\Before.xml` just zip them up and attach them here.

As for the numbering, that is by design. Microsoft haven't documented how they assign the display Ids so I've had to invent my own logic which obviously won't match theirs. For more info, read this: https://github.com/MartinGC94/DisplayConfig/issues/7

**Comment by waldner** [comment] 2024-11-12 10:09
Thanks, very interesting. On my system, for some reason that I haven't been able to understand (but there seem to be many people in the same situation), it seems that one display will alwas be disabled, and enabling it will disable another one, and so on. Nonetheless, all four are shown and can be acted upon in the windows settings, so it would be great if the same coud be done with DisplayConfig. As for the numbering, I think it's not vital since other criteria can be used to identify a display (eg the connection type).

So here's the XML for the setup I showed earlier (where display "2" is disabled - btw it looks like it's a displayport, not VGA, I couldn't check since it's a remote machine): 
[Before.xml.gz](https://github.com/user-attachments/files/17714733/Before.xml.gz)

When I enable display 2, display 4 gets disabled. Here's what happens:
![after](https://github.com/user-attachments/assets/d1a951c5-3266-4b15-b126-5bac63d44245)

and here's the XML for this: 
[After.xml.gz](https://github.com/user-attachments/files/17714750/After.xml.gz)

Let me know if you need me to do more tests or provide more information.

**Comment by MartinGC94** [comment] 2024-11-13 01:19
It seems to have been a regression I added in 3.1.0.  
I added a check to ensure I wouldn't add a display with an existing ID to the list of available displays to avoid conflicting Ids when enabling a display but because your GPU only supports 2 display outputs this means that duplicate Ids are expected and I just need to handle that in the Enable-Display command code.

I'm attaching a test version here, can you give it a try and see if it actually works?
[3.1.1.zip](https://github.com/user-attachments/files/17724686/3.1.1.zip)
`Get-DisplayInfo` should of course show all 4 displays and you should be able to switch between displays 2 and 4 with `Enable-Display -DisplayId 2 -DisplayIdToDisable 4` or whatever the Ids my module will assign to those displays. You can also try it without the `DisplayIdToDisable` parameter. I'd expect it to throw an error but it would be nice to get a confirmation.

**Comment by waldner** [comment] 2024-11-13 13:36
Getting this while trying to import (surely I'm doing something wrong, I'm not that versed with PS):

```
> Import-Module .\DisplayConfig.psd1
Import-Module : Could not load file or assembly 'file:///C:\Users\admin\Desktop\3.1.1\DisplayConfig.dll' or one of its
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module .\DisplayConfig.psd1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by MartinGC94** [comment] 2024-11-13 14:59
Files downloaded in most browsers get a "Mark of the web" so you need to unblock the files as described here: https://stackoverflow.com/questions/34400546/could-not-load-file-or-assembly-operation-is-not-supported-exception-from-hres

Protip: Unblock the zip file and then extract the files so you don't have to unblock a bunch of files. Alternatively, use 7-zip to unzip because it doesn't apply the mark to the unzipped files.

**Comment by MartinGC94** [comment] 2024-11-13 22:26
No idea. I've ordered a dummy display plug so I can test out this limit myself. Expect an update next week where I've hopefully received it and learned something from it.

**Comment by waldner** [comment] 2024-11-13 22:39
I might be able to arrange remote VNC access to the machine for you, if you are interested.
My contact: look for the URL in my profile here: https://github.com/waldner, go to that page, scroll to the very bottom and click "contact", run the code you find (sorry but spam etc.) and you'll get one of my email addresses.
If not, I'll wait for you to carry out your tests. Thanks.

**Comment by MartinGC94** [comment] 2024-11-25 01:49
I have found the issue and a solution. The problem was that it's apparently important that the Id property for the new display matches the Id for the removed display. Before I just incremented the Id by one for each display to ensure they were unique.
Here is the fixed version, try it out and see if it works for you:
[3.2.zip](https://github.com/user-attachments/files/17896122/3.2.zip)

**Comment by waldner** [comment] 2024-11-25 14:13
Yes! It works now, I'm able to enable display 4 and disable display 2 in one go. Are you going to make a release on powershell gallery?

**Comment by MartinGC94** [comment] 2024-11-25 17:45
Yes, just wanted to confirm that it was actually fixed before making a release. I've just added 3.2 to the gallery.

**Closed by MartinGC94** 2024-11-25 17:45 UTC
